spring:
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/notices-service
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      group-id: notices-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
gateway:
  baseUrl: http://localhost:8000/gateway
  follow: /follow
  users: /users
  key: ZGtzb2FmamRhc3BvZmphZHdzZjtsa2prbGohQCNAKClfKmpA
logging:
  level:
    org.springframework.data.mongodb: DEBUG
